[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
labwork_marketplace = "EQKNXSBE6vUbtPBY1ibXPyWmLzrtXBZqUs9Fjqo19TkX"

[programs.mainnet]
labwork_marketplace = "CKZHwoUZTJEnGNK4piPxyysrhwLKnnrNoBmEHM9rLaD4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster  = "https://rpc.mainnet.x1.xyz"
wallet   = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"